### ISSUE TITLE
Register for a MangoPay account

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.org#5]
First step: [sign the MangoPay contract and send it by mail](https://www.mangopay.com/fr/demarrez/submit-your-app/).

Then there are [documents to upload](https://www.mangopay.com/fr/demarrez/submit-your-app/upload-your-kyc-docs/):

- [x] The signed bylaws of the organization – *Les statuts certifiés conformes de l’association*
- [x] Proof of registration of the organization – *Récépissé de déclaration de l’association* – **requires completion of #2**
- ~~VAT number (if applicable) – *Numéro de TVA de la société (si imposable)*~~
- [x] ID of the organization's representative – *La pièce d’identité du dirigeant habilité à engager le Partenaire*
- [x] Declaration on honor signed by the representative – *Une [Déclaration sur l’honneur](https://www.mangopay.com/terms/Mangopay_Declaration_Sur_LHonneur.pdf) complétée et signée par le dirigeant*
- [x] CV of the representative (LinkedIn PDF acceptable) – *Le CV du dirigeant (PDF LinkedIn acceptés)*
- [x] Extract of the representative's criminal record – *Une extrait du casier judiciaire du dirigeant*
- [x] Your terms of service, signed – *vos CGU signées et paraphées* – **requires completion of #4**
- [x] Our BIC and IBAN – *Votre BIC et IBAN* – **requires completion of #3**

We also have to [add MangoPay's terms and the "Powered by" logos](https://www.mangopay.com/fr/demarrez/submit-your-app/publish-our-tcs/) to liberapay.com.

Finally, [submit our application](https://www.mangopay.com/fr/demarrez/submit-your-app/go-live/).

**Comment by finkiki** [comment]
What about bitcoins ?

**Comment by Changaco** [comment]
@finkiki Supporting cryptocoins is not in my priorities, but feel free to open a new issue and explain why you think it should be.

**Comment by finkiki** [comment]
I just remember old gratipay allowed bitcoins payments and as you fork it, code is already here. No ?

**Comment by Changaco** [comment]
@finkiki No. Gratipay never had automatic bitcoin payments, it was a manual process. More importantly, while Gratipay holds the funds of its users in its own bank account, Liberapay won't, they'll be held by MangoPay, which means that we can't easily implement payment methods beyond those that MangoPay provides.

**Comment by Changaco** [comment]
[The MangoPay contract in a nutshell](https://www.mangopay.com/obligations/)

**Comment by SimonSarazin** [comment]
Any chance to get a payroll system as gratipay wants to do or this will not be possible with mangopay ?

**Comment by Changaco** [comment]
@SimonSarazin Liberapay has teams similar to those Gittip had. Since the idea of teams is that they don't have a legal existence, they can't actually handle money, so I've modified the system to transfer the money directly from the donors to the members of the team, instead of passing through the team in-between.

**Comment by SimonSarazin** [comment]
It's maybe not the good thread to discuss about that, but don't you think we could get this possible but as an indication for the team, not as a direct payment ? The owner could after that decide how to give this money, for example by asking an invoice. We could provide a tool to help people to distribute the money, but just as an indication. That's what i actually do on my projects, but using spreasheets. I now have 6 spreadsheet, one for each project... It could be super to get it directly on liberapay : https://docs.google.com/spreadsheets/d/153wK4wyuMrqplYIakrCWh34dDRzik_56_F6UxjnW-R4/edit?usp=sharing

**Comment by Changaco** [comment]
@SimonSarazin You seem to be requesting a new feature, so you should [open an issue in the liberapay.com repo](https://github.com/liberapay/liberapay.com/issues/new), or come clarify what you want on IRC and I'll open the issue for you.

**Comment by Changaco** [comment]
I just realized that I don't actually have @Zatalyz's explicit approval to sign this contract, so I'm filling it but I'll wait before signing and sending it.

**Comment by Zatalyz** [comment]
I am agree, so sign it :)

**Comment by Changaco** [comment]
I've posted the contract this morning, it should arrive sometime next week.

**Comment by finkiki** [comment]
La partie déclaration sur l'honneur me paraît délirante. On ne pas utiliser MangoPay si on a une boîte qui a fait faillite ? si on a un antécédent judiciaire ?
Ee plus, il faut avoir fait l'objet d'une évaluation de sa réputation professionnelle ???

**Comment by Changaco** [comment]
It's a [CSSF](https://en.wikipedia.org/wiki/Commission_de_Surveillance_du_Secteur_Financier) form, not something specific to MangoPay, but I agree that it's a bit much. It doesn't look like an evaluation is mandatory, it says "if applicable".

**Comment by Changaco** [comment]
I have all the paperwork ready. They're asking for the URL to our terms of service, so I'll finish completing the /about pages before uploading the documents.

**Comment by Changaco** [comment]
"Thank you for your submission – we have successfully received your documents."

**Comment by Changaco** [comment]
I've submitted the final form. Now we wait…

**Comment by Changaco** [comment]
I got an email from their compliance team confirming that they've received everything including the contract sent by mail, and asking if we have a VAT number. I said we don't have one.

**Comment by Changaco** [comment]
And I just got a second email saying that our production account has been activated. \o/ \o/ \o/
